<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="decorator" nsURI="http://www.example.org/decorator" nsPrefix="decorator">
  <eSubpackages name="Decorator">
    <eClassifiers xsi:type="ecore:EClass" name="NNTrainerWithStatsInterface" abstract="true"
        eSuperTypes="#//Decorator/NNTrainerInterface">
      <eOperations name="train"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NNTrainerWithStats" eSuperTypes="#//Decorator/NNTrainerWithStatsInterface">
      <eOperations name="train"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NNTrainer" eSuperTypes="#//Decorator/NNTrainerInterface">
      <eOperations name="train"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NNTrainerInterface" abstract="true"
        interface="true">
      <eOperations name="train"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
